# Generated by Django 3.2.5 on 2021-07-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='avatar',
            field=models.FileField(blank=True, default='default_profile320.png', null=True, upload_to='profile/avatar/'),
        ),
    ]
