# Generated by Django 3.2.5 on 2021-08-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_count',
            field=models.IntegerField(default=1),
        ),
    ]
